### ISSUE TITLE
Не произойдёт повторный запрос

### ISSUE THREAD

**Issue by Vitaly-Ku** [mezhevikin/AppReview#2]
Допустим, хочу показывать запрос по такой логике

AppReview.requestIf(launches: 5)
AppReview.requestIf(launches: 25)

При launches: 5 нажал 'Not now', в результате чего, не проходят последующие проверки в isNeeded а именно: 
- lastReviewDate == nil
- lastReviewVersion != version

как итог - при launches: 25 запрос не сработает

**Comment by mezhevikin** [comment]
По такой логике не получиться в силу ограничений самого SKStoreReviewController.requestReview. Его нельзя вызывать когда хочешь, а только не чаще раз в 125 дней, при этом версия приложения должна отличаться. 

Возможно мне следует переименовать параметр launches в minLaunches чтобы он явно отображал суть 

`AppReview.requestIf(minLaunches: 5)`

**Comment by mezhevikin** [comment]
При этом следует отметить что повторный запрос оценки будет сам вызываться через 125 дней после последнего запроса. Это библиотека учитывает

```
 public var isNeeded: Bool {
        launches >= minLaunches &&
        daysAfterFirstLaunch >= minDays &&
        (lastReviewDate == nil || daysAfterLastReview >= 125) &&
        lastReviewVersion != version
    }
```
